package:
  name: roq-algo
  version: 1.0

source:
  git_url: ..

build:
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - roq-autogen
  host:
    - catch2
    - libabseil
    - roq-client
    - roq-flags

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Strategy (a template project)
